name: fl_pages
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  basic_utils: ^4.2.0
  desktop_window: ^0.4.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.1
  gap: ^2.0.0
  go_router: ^3.0.2
  google_fonts: ^2.3.1
  hooks_riverpod: ^1.0.3
  logger: ^1.0.0
  package_info: ^2.0.2
  reactive_forms: ^11.0.1
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  all_lint_rules_community: ^0.0.7
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
